.\" Manpage for xcp-v6d.
.\" Contact mike.mcclurg@citrix.com to correct errors or typos.
.TH man 1 "02 Dec 2011" "1.3" "xcp-v6d man page"
.SH NAME
xcp-v6d \- Feature daemon for XCP
.SH SYNOPSIS
.B xcp-v6d
.SH DESCRIPTION
This daemon communicates with XCP's xapi server over XML-RPC to enable or disable certain features of XCP. Currently, all XCP features are enabled. In the future, this daemon will allow users to enable "experimental" features of XCP, which might be functional but not quite ready for production use.
.SH "SEE ALSO"
xcp-xapi(1)
.SH BUGS
Please report bugs to the xen-api@lists.xensource.com mailing list.
.SH AUTHOR
Jonathan Ludlam <jonathan.ludlam@eu.citrix.com>
