(executable
 (modes exe)
 (name fe_main)
 ; belong to the package, so that dune-build-info reports its version
 (public_name -)
 (package xapi-forkexecd)
 (libraries
   astring
   fd-send-recv
   forkexec
   unix
   uuid
   xapi-log
   xapi-stdext-unix
  ))

(install
 (package xapi-forkexecd)
 (section sbin)
 (files (fe_main.exe as forkexecd)))
