(*
 * Copyright (c) Cloud Software Group, Inc.
 *)

open Printf
open Datamodel
open Datamodel_types
open Common_functions
open CommonFunctions
module DT = Datamodel_types
module DU = Datamodel_utils

module TypeSet = Set.Make (struct
  type t = DT.ty

  let compare = compare
end)

let srcdir = "autogen-out/src"

type cmdlet = {cmdletname: string; content: string}

let cmdlets_to_export = ref []

let maps = ref TypeSet.empty

let rec is_last x list =
  match list with
  | [] ->
      false
  | hd :: [] ->
      if hd = x then
        true
      else
        false
  | hd :: tl ->
      if hd = x then
        false
      else
        is_last x tl

let rec main () =
  let json =
    `O
      [
        ( "all_classes"
        , `A
            (List.map
               (fun x ->
                 `O
                   [
                     ("exposed_name", `String (exposed_class_name x.name))
                   ; ( "var_name"
                     , `String (ocaml_class_to_csharp_local_var x.name)
                     )
                   ]
               )
               classes
            )
        )
      ]
  in
  render_file
    ("ConvertTo-XenRef.mustache", "ConvertTo-XenRef.cs")
    json templdir srcdir ;

  http_actions
  |> List.filter (fun (_, (_, _, sdk, _, _, _)) -> sdk)
  |> List.iter gen_http_action ;

  let filtered_classes = List.filter generated classes in
  let cmdlets = List.concat_map gen_cmdlets filtered_classes in

  List.iter (fun x -> write_file x.cmdletname x.content) cmdlets ;

  filtered_classes |> List.iter gen_destructor ;

  cmdlets_to_export :=
    [
      "Connect-XenServer"
    ; "Disconnect-XenServer"
    ; "Get-XenSession"
    ; "Receive-XenPoolPatch"
    ; "Send-XenOemPatchStream"
    ; "Wait-XenTask"
    ; "ConvertTo-XenRef"
    ]
    @ !cmdlets_to_export ;

  cmdlets_to_export := List.sort String.compare !cmdlets_to_export ;

  let module_json =
    `O
      [
        ( "cmdlets_to_export"
        , `A
            (List.map
               (fun x ->
                 `O
                   [
                     ("cmdlet_to_export", `String x)
                   ; ("is_last", `Bool (is_last x !cmdlets_to_export))
                   ]
               )
               !cmdlets_to_export
            )
        )
      ]
  in
  render_file
    ("XenServerPSModule.mustache", "XenServerPSModule.psd1")
    module_json templdir destdir ;

  Gen_powershell_help.gen_help ()

(****************)
(* Http actions *)
(****************)

(* Shared by the cmdlet template and the generated help, so that the two cannot
   disagree about what an HTTP action's query arguments are called. *)
and gen_http_action action =
  let name, (meth, uri, _, args, _, _) = action in
  let commonVerb = get_http_action_verb name meth in
  let verbCategory = get_common_verb_category commonVerb in
  let stem = get_http_action_stem name in
  let arg_name = http_arg_name in
  let arg_type = http_arg_type in
  let json =
    `O
      [
        ("verb_category", `String verbCategory)
      ; ("common_verb", `String commonVerb)
      ; ("stem", `String stem)
      ; ("isPut", `Bool (meth == Put))
      ; ("isGet", `Bool (meth == Get))
      ; ("uri", `String uri)
      ; ("action_name", `String name)
      ; ( "args"
        , `A
            (List.map
               (fun x ->
                 `O
                   [
                     ("arg_type", `String (arg_type x))
                   ; ("arg_name", `String (arg_name x))
                   ; ( "from_pipeline"
                     , `Bool (String.lowercase_ascii (arg_name x) = "uuid")
                     )
                   ]
               )
               args
            )
        )
      ]
  in
  let cmdlet_name = sprintf "%s-Xen%s" commonVerb stem in
  render_file
    ("HttpAction.mustache", sprintf "%s.cs" cmdlet_name)
    json templdir srcdir ;
  cmdlets_to_export := cmdlet_name :: !cmdlets_to_export

(*************************)
(* Autogenerated cmdlets *)
(*************************)
and gen_cmdlets obj =
  let {name= classname; messages; _} = obj in
  let stem = ocaml_class_to_csharp_class classname in

  let cmdlets =
    [
      {cmdletname= sprintf "Get-Xen%s" stem; content= gen_class obj classname}
    ; {
        cmdletname= sprintf "New-Xen%s" stem
      ; content=
          gen_constructor obj classname (List.filter is_constructor messages)
      }
    ; {
        cmdletname= sprintf "Remove-Xen%sProperty" stem
      ; content= gen_remover obj classname (List.filter is_remover messages)
      }
    ; {
        cmdletname= sprintf "Add-Xen%s" stem
      ; content= gen_adder obj classname (List.filter is_adder messages)
      }
    ; {
        cmdletname= sprintf "Set-Xen%s" stem
      ; content= gen_setter obj classname (List.filter is_setter messages)
      }
    ; {
        cmdletname= sprintf "Get-Xen%sProperty" stem
      ; content= gen_getter obj classname (List.filter is_getter messages)
      }
    ; {
        cmdletname= sprintf "Invoke-Xen%s" stem
      ; content= gen_invoker obj classname (List.filter is_invoke messages)
      }
    ]
  in

  cmdlets |> List.filter (fun x -> x.content <> "")

and write_file cmdletname content =
  let filename = sprintf "%s.cs" cmdletname in
  let fn = Filename.concat srcdir filename in
  cmdlets_to_export := cmdletname :: !cmdlets_to_export ;
  with_output fn (fun x -> output_string x content)

(*********************************)
(* Print function for Get-XenFoo *)
(*********************************)
and render_to_string template_name json =
  let path = Filename.concat templdir template_name in
  let templ = string_of_file path |> Mustache.of_string in
  Mustache.render templ json

and gen_class obj classname =
  if List.mem classname classes_with_records then
    let json =
      `O
        [
          ("licence", `String Licence.bsd_two_clause)
        ; ("class", `String (ocaml_class_to_csharp_class classname))
        ; ("qualified_type", `String (qualified_class_name classname))
        ; ( "params"
          , `String (print_xenobject_params obj classname false false true)
          )
        ; ("has_uuid", `Bool (has_uuid obj))
        ; ("has_name", `Bool (has_name obj))
        ]
    in
    render_to_string "Get-XenObject.mustache" json
  else
    ""

(*********************************)
(* Print function for New-XenFoo *)
(*********************************)
and gen_constructor obj classname messages =
  match messages with
  | [] ->
      ""
  | [message] ->
      let fields_or_params =
        if is_real_constructor message then
          gen_fields (DU.fields_of_obj obj)
        else
          gen_constructor_params message.msg_params
      in
      let async_param_override =
        if message.msg_async then
          "\n\
          \        protected override bool GenerateAsyncParam\n\
          \        {\n\
          \            get { return true; }\n\
          \        }\n"
        else
          ""
      in
      let make =
        if is_real_constructor message then
          gen_make_record obj classname
        else
          gen_make_fields message obj
      in
      let json =
        `O
          [
            ("licence", `String Licence.bsd_two_clause)
          ; ("class", `String (ocaml_class_to_csharp_class classname))
          ; ("qualified_type", `String (qualified_class_name classname))
          ; ("async_task", `Bool message.msg_async)
          ; ("fields_or_params", `String fields_or_params)
          ; ("async_param_override", `String async_param_override)
          ; ("make", `String make)
          ; ( "shouldprocess"
            , `String (gen_shouldprocess "New" message classname)
            )
          ; ("open_brace", `String "{")
          ; ( "api_call"
            , `String (gen_csharp_api_call message classname "New" "passthru")
            )
          ]
      in
      render_to_string "New-XenObject.mustache" json
  | _ ->
      assert false

and gen_constructor_params params =
  match params with
  | [] ->
      ""
  | hd :: tl ->
      sprintf "%s\n%s"
        (gen_constructor_param hd.param_name hd.param_type ["Fields"])
        (gen_constructor_params tl)

and gen_fields fields =
  match fields with
  | [] ->
      ""
  | hd :: tl -> (
    match hd.qualifier with
    | DynamicRO ->
        gen_fields tl
    | _ ->
        sprintf "%s\n%s"
          (gen_constructor_param (full_name hd) hd.ty ["Fields"])
          (gen_fields tl)
  )

and gen_constructor_param paramName paramType paramsets =
  let publicName = ocaml_class_to_csharp_property paramName in
  (*Do not add a Record parameter; it has already been added manually as all constructors need one*)
  if paramName = "record" then
    ""
  else
    sprintf "\n        %s\n        public %s %s { get; set; }"
      (print_parameter_sets paramsets)
      (obj_internal_type paramType)
      publicName

and gen_make_record obj classname =
  sprintf
    "\n\
    \            if (Record == null && HashTable == null)\n\
    \            {\n\
    \                Record = new %s();%s\n\
    \            }\n\
    \            else if (Record == null)\n\
    \            {\n\
    \                Record = new %s(HashTable);\n\
    \            }\n"
    (qualified_class_name classname)
    (gen_record_fields (DU.fields_of_obj obj))
    (qualified_class_name classname)

and gen_record_fields fields =
  match fields with
  | [] ->
      ""
  | h :: tl -> (
    match h.qualifier with
    | DynamicRO ->
        gen_record_fields tl
    | _ ->
        sprintf "\n                %s%s" (gen_record_field h)
          (gen_record_fields tl)
  )

and gen_record_field field =
  let chk =
    sprintf
      "if (MyInvocation.BoundParameters.ContainsKey(\"%s\"))\n                "
      (ocaml_field_to_csharp_property field)
  in
  let assignment =
    match field.ty with
    | Ref _ ->
        sprintf
          "    Record.%s = new %s(%s == null ? \"OpaqueRef:NULL\" : \
           %s.opaque_ref);"
          (full_name field)
          (obj_internal_type field.ty)
          (ocaml_field_to_csharp_property field)
          (ocaml_field_to_csharp_property field)
    | Map (u, v) ->
        sprintf
          "    Record.%s = \
           CommonCmdletFunctions.ConvertHashTableToDictionary<%s, %s>(%s);"
          (full_name field) (exposed_type u) (exposed_type v)
          (pascal_case (full_name field))
    | _ ->
        sprintf "    Record.%s = %s;" (full_name field)
          (ocaml_field_to_csharp_property field)
  in
  chk ^ assignment

and gen_make_fields message obj =
  sprintf
    "\n\
    \            if (Record != null)\n\
    \            {%s\n\
    \            }\n\
    \            else if (HashTable != null)\n\
    \            {%s\n\
    \            }"
    (explode_record_fields message (DU.fields_of_obj obj))
    (explode_hashtable_fields message (DU.fields_of_obj obj))

and explode_record_fields message fields =
  let print_map tl hd =
    sprintf
      "\n\
      \                %s = \
       CommonCmdletFunctions.ConvertDictionaryToHashtable(Record.%s);%s"
      (ocaml_class_to_csharp_property (full_name hd))
      (full_name hd)
      (explode_record_fields message tl)
  in
  let print_record tl hd =
    sprintf "\n                %s = Record.%s;%s"
      (ocaml_class_to_csharp_property (full_name hd))
      (full_name hd)
      (explode_record_fields message tl)
  in
  match fields with
  | [] ->
      ""
  | hd :: tl ->
      if List.exists (fun x -> full_name hd = x.param_name) message.msg_params
      then
        match hd.ty with
        | Map (_, _) ->
            print_map tl hd
        | _ ->
            print_record tl hd
      else
        explode_record_fields message tl

and explode_hashtable_fields message fields =
  match fields with
  | [] ->
      ""
  | hd :: tl ->
      if List.exists (fun x -> full_name hd = x.param_name) message.msg_params
      then
        sprintf "\n                %s = %s;%s"
          (ocaml_class_to_csharp_property (full_name hd))
          (convert_from_hashtable (full_name hd) hd.ty)
          (explode_hashtable_fields message tl)
      else
        explode_hashtable_fields message tl

and convert_from_hashtable fname ty =
  let field = sprintf "\"%s\"" fname in
  match ty with
  | DateTime ->
      sprintf "Marshalling.ParseDateTime(HashTable, %s)" field
  | Bool ->
      sprintf "Marshalling.ParseBool(HashTable, %s)" field
  | Float ->
      sprintf "Marshalling.ParseDouble(HashTable, %s)" field
  | Int ->
      sprintf "Marshalling.ParseLong(HashTable, %s)" field
  | Ref name ->
      sprintf "Marshalling.ParseRef<%s>(HashTable, %s)"
        (exposed_class_name name) field
  | SecretString | String ->
      sprintf "Marshalling.ParseString(HashTable, %s)" field
  | Set String ->
      sprintf "Marshalling.ParseStringArray(HashTable, %s)" field
  | Set (Ref x) ->
      sprintf "Marshalling.ParseSetRef<%s>(HashTable, %s)"
        (exposed_class_name x) field
  | Set (Enum (x, _)) ->
      sprintf
        "Helper.StringArrayToEnumList<%s>(Marshalling.ParseStringArray(HashTable, \
         %s))"
        x field
  | Enum (x, _) ->
      sprintf
        "(%s)CommonCmdletFunctions.EnumParseDefault(typeof(%s), \
         Marshalling.ParseString(HashTable, %s))"
        x x field
  | Map (Ref x, Record _) ->
      sprintf "Marshalling.ParseMapRefRecord<%s, Proxy_%s>(HashTable, %s)"
        (exposed_class_name x) (exposed_class_name x) field
  | Map (_, _) as x ->
      maps := TypeSet.add x !maps ;
      sprintf "(Marshalling.ParseHashTable(HashTable, %s))" field
  | Record name ->
      sprintf "new %s((Proxy_%s)HashTable[%s])" (exposed_class_name name)
        (exposed_class_name name) field
  | Set (Record name) ->
      sprintf "Helper.Proxy_%sArrayTo%sList(Marshalling.ParseStringArray(%s))"
        (exposed_class_name name) (exposed_class_name name) field
  | _ ->
      assert false

(************************************)
(* Print function for Remove-XenFoo *)
(************************************)

and gen_destructor obj =
  let {name= classname; messages; _} = obj in
  let destructors = List.filter is_destructor messages in
  match destructors with
  | [] ->
      ()
  | [x] ->
      let json =
        `O
          [
            ("type", `String (qualified_class_name classname))
          ; ("wire_class_name", `String (exposed_class_name classname))
          ; ("class_name", `String (ocaml_class_to_csharp_class classname))
          ; ("property", `String (ocaml_class_to_csharp_property classname))
          ; ("type_local", `String (ocaml_class_to_csharp_local_var classname))
          ; ("async", `Bool x.msg_async)
          ; ("has_uuid", `Bool (has_uuid obj))
          ; ("has_name", `Bool (has_name obj))
          ]
      in
      let cmdlet_name =
        sprintf "Remove-Xen%s" (ocaml_class_to_csharp_class classname)
      in
      render_file
        ("Remove-XenObject.mustache", sprintf "%s.cs" cmdlet_name)
        json templdir srcdir ;
      cmdlets_to_export := cmdlet_name :: !cmdlets_to_export
  | _ ->
      assert false

(*****************************************)
(* Print function for Remove-XenFoo -Bar *)
(*****************************************)
and gen_message_family verb noun class_decl void_output obj classname messages =
  match messages with
  | [] ->
      ""
  | _ ->
      let cut_message_name x = cut_msg_name (pascal_case x.msg_name) verb in
      let asyncMessages =
        List.map cut_message_name (List.filter (fun x -> x.msg_async) messages)
      in
      let json =
        `O
          [
            ("licence", `String Licence.bsd_two_clause)
          ; ("verb", `String verb)
          ; ("noun", `String noun)
          ; ("qualified_type", `String (qualified_class_name classname))
          ; ("async_task", `Bool (asyncMessages <> []))
          ; ("void_output", `Bool void_output)
          ; ("class_decl", `String class_decl)
          ; ( "params"
            , `String (print_xenobject_params obj classname true true true)
            )
          ; ("async_param", `String (print_async_param asyncMessages))
          ; ( "message_params"
            , `String (gen_message_as_param classname verb messages)
            )
          ; ("local_var", `String (ocaml_class_to_csharp_local_var classname))
          ; ("property", `String (ocaml_class_to_csharp_property classname))
          ; ( "cmdlet_methods"
            , `String (print_cmdlet_methods classname messages verb)
            )
          ; ("passthru", `String (gen_passthru classname))
          ; ( "parse_method"
            , `String (print_parse_xenobject_private_method obj classname true)
            )
          ; ( "process_methods"
            , `String
                (print_process_record_private_methods classname messages verb "")
            )
          ]
      in
      render_to_string "Set-XenObject.mustache" json

(*****************************************)
(* Print function for Remove-XenFoo -Bar *)
(*****************************************)
and gen_remover obj classname messages =
  let stem = ocaml_class_to_csharp_class classname in
  gen_message_family "Remove"
    (sprintf "%sProperty" stem)
    (sprintf "RemoveXen%sProperty" stem)
    false obj classname messages

(**************************************)
(* Print function for Set-XenFoo -Bar *)
(**************************************)
and gen_setter obj classname messages =
  let stem = ocaml_class_to_csharp_class classname in
  gen_message_family "Set" stem (sprintf "SetXen%s" stem) true obj classname
    messages

(**************************************)
(* Print function for Add-XenFoo -Bar *)
(**************************************)
and gen_adder obj classname messages =
  let stem = ocaml_class_to_csharp_class classname in
  gen_message_family "Add" stem (sprintf "AddXen%s" stem) true obj classname
    messages

(*****************************************)
(* Print function for Invoke-XenFoo -Bar *)
(*****************************************)
and gen_invoker obj classname messages =
  match messages with
  | [] ->
      ""
  | _ ->
      let stem = ocaml_class_to_csharp_class classname in
      let messagesWithParams =
        List.filter (is_message_with_dynamic_params classname) messages
      in
      let json =
        `O
          [
            ("licence", `String Licence.bsd_two_clause)
          ; ("verb_expr", `String "VerbsLifecycle.Invoke")
          ; ("noun", `String stem)
          ; ("should_process", `String "true")
          ; ("class_decl", `String (sprintf "InvokeXen%s" stem))
          ; ("class", `String stem)
          ; ("enum_kind", `String "Action")
          ; ("open_brace", `String "{")
          ; ( "passthru_param"
            , `String
                "\n\
                \        [Parameter]\n\
                \        public SwitchParameter PassThru { get; set; }\n"
            )
          ; ( "params"
            , `String (print_xenobject_params obj classname true true true)
            )
          ; ( "dynamic_generator"
            , `String
                (print_dynamic_generator classname "Action" "Invoke"
                   messagesWithParams
                )
            )
          ; ("local_var", `String (ocaml_class_to_csharp_local_var classname))
          ; ("property", `String (ocaml_class_to_csharp_property classname))
          ; ( "cmdlet_methods_dynamic"
            , `String
                (print_cmdlet_methods_dynamic classname messages "Action"
                   "Invoke"
                )
            )
          ; ( "parse_method"
            , `String (print_parse_xenobject_private_method obj classname true)
            )
          ; ( "process_methods"
            , `String
                (print_process_record_private_methods classname messages
                   "Invoke" "passthru"
                )
            )
          ; ("messages_enum", `String (print_messages_as_enum "Invoke" messages))
          ; ( "dynamic_params"
            , `String
                (print_dynamic_params classname "Action" "Invoke"
                   messagesWithParams
                )
            )
          ]
      in
      render_to_string "Invoke-XenObject.mustache" json

(**********************************************)
(* Print function for Get-XenFooProperty -Bar *)
(**********************************************)
and gen_getter obj classname messages =
  match messages with
  | [] ->
      ""
  | _ ->
      let stem = ocaml_class_to_csharp_class classname in
      let messagesWithParams =
        List.filter (is_message_with_dynamic_params classname) messages
      in
      let json =
        `O
          [
            ("licence", `String Licence.bsd_two_clause)
          ; ("verb_expr", `String "VerbsCommon.Get")
          ; ("noun", `String (sprintf "%sProperty" stem))
          ; ("should_process", `String "false")
          ; ("class_decl", `String (sprintf "GetXen%sProperty" stem))
          ; ("class", `String stem)
          ; ("enum_kind", `String "Property")
          ; ("open_brace", `String "{")
          ; ("passthru_param", `String "")
          ; ( "params"
            , `String (print_xenobject_params obj classname true true false)
            )
          ; ( "dynamic_generator"
            , `String
                (print_dynamic_generator classname "Property" "Get"
                   messagesWithParams
                )
            )
          ; ("local_var", `String (ocaml_class_to_csharp_local_var classname))
          ; ("property", `String (ocaml_class_to_csharp_property classname))
          ; ( "cmdlet_methods_dynamic"
            , `String
                (print_cmdlet_methods_dynamic classname messages "Property"
                   "Get"
                )
            )
          ; ( "parse_method"
            , `String (print_parse_xenobject_private_method obj classname false)
            )
          ; ( "process_methods"
            , `String
                (print_process_record_private_methods classname messages "Get"
                   "pipe"
                )
            )
          ; ("messages_enum", `String (print_messages_as_enum "Get" messages))
          ; ( "dynamic_params"
            , `String
                (print_dynamic_params classname "Property" "Get"
                   messagesWithParams
                )
            )
          ]
      in
      render_to_string "Invoke-XenObject.mustache" json

and print_cmdlet_methods_dynamic classname messages enum commonVerb =
  let cut_message_name x = cut_msg_name (pascal_case x.msg_name) commonVerb in
  let localVar = ocaml_class_to_csharp_local_var classname in
  match messages with
  | [] ->
      ""
  | hd :: tl ->
      sprintf
        "\n\
        \                case Xen%s%s.%s:\n\
        \                    ProcessRecord%s(%s);\n\
        \                    break;%s"
        (ocaml_class_to_csharp_class classname)
        enum (cut_message_name hd) (cut_message_name hd) localVar
        (print_cmdlet_methods_dynamic classname tl enum commonVerb)

(**************************************)
(* Common to more than one generators *)
(**************************************)
and gen_passthru classname =
  sprintf
    "if (!PassThru)\n\
    \                return;\n\n\
    \            RunApiCall(() =>\n\
    \                {\n\
    \                    var contxt = _context as \
     XenServerCmdletDynamicParameters;\n\n\
    \                    if (contxt != null && contxt.Async)\n\
    \                    {\n\
    \                        XenAPI.Task taskObj = null;\n\
    \                        if (taskRef != null && taskRef != \
     \"OpaqueRef:NULL\")\n\
    \                        {\n\
    \                            taskObj = XenAPI.Task.get_record(session, \
     taskRef.opaque_ref);\n\
    \                            taskObj.opaque_ref = taskRef.opaque_ref;\n\
    \                        }\n\n\
    \                        WriteObject(taskObj, true);\n\
    \                    }\n\
    \                    else\n\
    \                    {\n\n\
    \                        var obj = %s.get_record(session, %s);\n\
    \                        if (obj != null)\n\
    \                            obj.opaque_ref = %s;\n\
    \                        WriteObject(obj, true);\n\n\
    \                    }\n\
    \                });"
    (qualified_class_name classname)
    (ocaml_class_to_csharp_local_var classname)
    (ocaml_class_to_csharp_local_var classname)

and print_dynamic_generator classname enum commonVerb messagesWithParams =
  match messagesWithParams with
  | [] ->
      ""
  | _ ->
      sprintf
        "\n\
        \        public override object GetDynamicParameters()\n\
        \        {\n\
        \            switch (Xen%s)\n\
        \            {%s\n\
        \                default:\n\
        \                    return null;\n\
        \            }\n\
        \        }\n"
        enum
        (print_messages_with_params classname enum commonVerb messagesWithParams)

and print_messages_with_params classname enum commonVerb x =
  match x with
  | [] ->
      ""
  | hd :: tl ->
      sprintf
        "\n\
        \                case Xen%s%s.%s:\n\
        \                    _context = new Xen%s%s%sDynamicParameters();\n\
        \                    return _context;%s"
        (ocaml_class_to_csharp_class classname)
        enum
        (cut_msg_name (pascal_case hd.msg_name) commonVerb)
        (ocaml_class_to_csharp_class classname)
        enum
        (cut_msg_name (pascal_case hd.msg_name) commonVerb)
        (print_messages_with_params classname enum commonVerb tl)

and print_dynamic_params classname enum commonVerb messagesWithParams =
  match messagesWithParams with
  | [] ->
      ""
  | hd :: tl ->
      sprintf
        "\n\
        \    public class Xen%s%s%sDynamicParameters : \
         IXenServerDynamicParameter\n\
        \    {%s%s\n\
        \    }\n\
         %s"
        (ocaml_class_to_csharp_class classname)
        enum
        (cut_msg_name (pascal_case hd.msg_name) commonVerb)
        ( if hd.msg_async then
            "\n\
            \        [Parameter]\n\
            \        public SwitchParameter Async { get; set; }\n"
          else
            ""
        )
        (print_dynamic_param_members classname hd.msg_params commonVerb
           (overload_tracked_params hd classname commonVerb)
        )
        (print_dynamic_params classname enum commonVerb tl)

and print_dynamic_param_members classname params commonVerb tracked =
  match params with
  | [] ->
      ""
  | hd :: tl ->
      if is_class hd classname then
        print_dynamic_param_members classname tl commonVerb tracked
      else
        let publicProperty = dynamic_param_property commonVerb hd in
        let theType = obj_internal_type hd.param_type in
        let rest =
          print_dynamic_param_members classname tl commonVerb tracked
        in
        if List.mem hd.param_name tracked then
          (* Which overload to call depends on whether the caller set this, so
             record that rather than relying on the value being non-default. *)
          sprintf
            "\n\
            \        [Parameter]\n\
            \        public %s %s\n\
            \        {\n\
            \            get => _%s;\n\
            \            set\n\
            \            {\n\
            \                _%s = value;\n\
            \                Is%sSpecified = true;\n\
            \            }\n\
            \        }\n\n\
            \        private %s _%s;\n\n\
            \        internal bool Is%sSpecified;\n\
             %s "
            theType publicProperty publicProperty publicProperty publicProperty
            theType publicProperty publicProperty rest
        else
          sprintf
            "\n        [Parameter]\n        public %s %s { get; set; }\n%s "
            theType publicProperty rest

and print_messages_as_enum commonVerb messages =
  let cut_message_name x = cut_msg_name (pascal_case x.msg_name) commonVerb in
  match messages with
  | [] ->
      ""
  | [x] ->
      sprintf "\n        %s" (cut_message_name x)
  | hd :: tl ->
      sprintf "\n        %s,%s" (cut_message_name hd)
        (print_messages_as_enum commonVerb tl)

and gen_message_as_param classname commonVerb messages =
  match messages with
  | [] ->
      ""
  | hd :: tl ->
      let msgType = get_message_type hd classname commonVerb in
      let cutMessageName = cut_msg_name (pascal_case hd.msg_name) commonVerb in
      let msgName =
        if cutMessageName = "Host" then
          "XenHost"
        else
          cutMessageName
      in
      sprintf
        "\n\
        \        [Parameter]\n\
        \        public %s %s\n\
        \        {\n\
        \            get { return %s; }\n\
        \            set\n\
        \            {\n\
        \                %s = value;\n\
        \                %sIsSpecified = true;\n\
        \            }\n\
        \        }\n\
        \        private %s %s;\n\
        \        private bool %sIsSpecified;\n\
         %s"
        msgType msgName
        (lower_and_underscore_first msgName)
        (lower_and_underscore_first msgName)
        (lower_and_underscore_first msgName)
        msgType
        (lower_and_underscore_first msgName)
        (lower_and_underscore_first msgName)
        (gen_message_as_param classname commonVerb tl)

and print_cmdlet_methods classname messages commonVerb =
  let cut_message_name x = cut_msg_name (pascal_case x.msg_name) commonVerb in
  let switch_name x =
    if cut_message_name x = "Host" then
      "XenHost"
    else
      cut_message_name x
  in
  let localVar = ocaml_class_to_csharp_local_var classname in
  match messages with
  | [] ->
      ""
  | [x] ->
      sprintf "if (%sIsSpecified)\n                ProcessRecord%s(%s);"
        (lower_and_underscore_first (switch_name x))
        (cut_message_name x) localVar
  | hd :: tl ->
      sprintf
        "if (%sIsSpecified)\n\
        \                ProcessRecord%s(%s);\n\
        \            %s"
        (lower_and_underscore_first (switch_name hd))
        (cut_message_name hd) localVar
        (print_cmdlet_methods classname tl commonVerb)

and print_xenobject_params obj classname mandatoryRef includeXenObject
    includeUuidAndName =
  let publicName = ocaml_class_to_csharp_property classname in
  sprintf
    "%s\n\n\
    \        [Parameter(ParameterSetName = \"Ref\"%s, \
     ValueFromPipelineByPropertyName = true, Position = 0)]\n\
    \        [Alias(\"opaque_ref\")]\n\
    \        public XenRef<%s> Ref { get; set; }\n\
     %s%s\n"
    ( if includeXenObject then
        print_param_xen_object (qualified_class_name classname) publicName
      else
        ""
    )
    ( if mandatoryRef then
        ", Mandatory = true"
      else
        ""
    )
    (qualified_class_name classname)
    (print_param_uuid (has_uuid obj && includeUuidAndName))
    (print_param_name (has_name obj && includeUuidAndName))

and print_param_xen_object qualifiedClassName publicName =
  sprintf
    "\n\
    \        [Parameter(ParameterSetName = \"XenObject\", Mandatory = true, \
     ValueFromPipeline = true, Position = 0)]\n\
    \        public %s %s { get; set; }"
    qualifiedClassName publicName

and print_param_uuid hasUuid =
  if hasUuid then
    sprintf
      "\n\
      \        [Parameter(ParameterSetName = \"Uuid\", Mandatory = true, \
       ValueFromPipelineByPropertyName = true, Position = 0)]\n\
      \        public Guid Uuid { get; set; }\n"
  else
    sprintf ""

and print_param_name hasName =
  if hasName then
    sprintf
      "\n\
      \        [Parameter(ParameterSetName = \"Name\", Mandatory = true, \
       ValueFromPipelineByPropertyName = true, Position = 0)]\n\
      \        [Alias(\"name_label\")]\n\
      \        public string Name { get; set; }\n"
  else
    sprintf ""

and print_async_param asyncMessages =
  match asyncMessages with
  | [] ->
      ""
  | _ ->
      sprintf
        "\n\
        \        protected override bool GenerateAsyncParam\n\
        \        {\n\
        \            get\n\
        \            {\n\
        \                return %s;\n\
        \            }\n\
        \        }\n"
        (condition asyncMessages)

and condition messages =
  match messages with
  | [] ->
      ""
  | [x] ->
      sprintf "%sIsSpecified" (lower_and_underscore_first x)
  | hd :: tl ->
      sprintf "%sIsSpecified\n                       ^ %s"
        (lower_and_underscore_first hd)
        (condition tl)

and print_parameter_sets parameterSets =
  match parameterSets with
  | [] ->
      "[Parameter]"
  | [x] ->
      sprintf "[Parameter(ParameterSetName = \"%s\")]" x
  | hd :: tl ->
      sprintf "[Parameter(ParameterSetName = \"%s\")]\n        %s" hd
        (print_parameter_sets tl)

and print_parse_xenobject_private_method obj classname includeUuidAndName =
  let publicProperty = ocaml_class_to_csharp_property classname in
  let localVar = ocaml_class_to_csharp_local_var classname in
  sprintf
    "\n\
    \        private string Parse%s()\n\
    \        {\n\
    \            string %s = null;\n\n\
    \            if (%s != null)\n\
    \                %s = (new XenRef<%s>(%s)).opaque_ref;%s%s\n\
    \            else if (Ref != null)\n\
    \                %s = Ref.opaque_ref;\n\
    \            else\n\
    \            {\n\
    \                ThrowTerminatingError(new ErrorRecord(\n\
    \                    new ArgumentException(\"At least one of the \
     parameters '%s', 'Ref'%s must be set\"),\n\
    \                    string.Empty,\n\
    \                    ErrorCategory.InvalidArgument,\n\
    \                    %s));\n\
    \            }\n\n\
    \            return %s;\n\
    \        }\n"
    publicProperty localVar publicProperty localVar
    (qualified_class_name classname)
    publicProperty
    ( if has_uuid obj && includeUuidAndName then
        sprintf
          "\n\
          \            else if (Uuid != Guid.Empty)\n\
          \            {\n\
          \                var xenRef = %s.get_by_uuid(session, \
           Uuid.ToString());\n\
          \                if (xenRef != null)\n\
          \                    %s = xenRef.opaque_ref;\n\
          \            }"
          (qualified_class_name classname)
          localVar
      else
        sprintf ""
    )
    ( if has_name obj && includeUuidAndName then
        sprintf
          "\n\
          \            else if (Name != null)\n\
          \            {\n\
          \                var xenRefs = %s.get_by_name_label(session, Name);\n\
          \                if (xenRefs.Count == 1)\n\
          \                    %s = xenRefs[0].opaque_ref;\n\
          \                else if (xenRefs.Count > 1)\n\
          \                    ThrowTerminatingError(new ErrorRecord(\n\
          \                        new ArgumentException(string.Format(\"More \
           than one %s with name label {0} exist\", Name)),\n\
          \                        string.Empty,\n\
          \                        ErrorCategory.InvalidArgument,\n\
          \                        Name));\n\
          \            }"
          (qualified_class_name classname)
          localVar
          (qualified_class_name classname)
      else
        sprintf ""
    )
    localVar publicProperty
    ( if has_uuid obj then
        sprintf ", 'Uuid'"
      else
        sprintf ""
    )
    publicProperty localVar

and print_process_record_private_methods classname messages commonVerb switch =
  match messages with
  | [] ->
      sprintf ""
  | hd :: tl ->
      let cutMessageName = cut_msg_name (pascal_case hd.msg_name) commonVerb in
      sprintf
        "\n\
        \        private void ProcessRecord%s(string %s)\n\
        \        {%s%s\n\
        \            RunApiCall(()=>\n\
        \            {%s\n\
        \            });\n\
        \        }\n\
         %s"
        cutMessageName
        (ocaml_class_to_csharp_local_var classname)
        ""
        (gen_shouldprocess commonVerb hd classname)
        (gen_csharp_api_call hd classname commonVerb switch)
        (print_process_record_private_methods classname tl commonVerb switch)

and gen_shouldprocess commonVerb message classname =
  match commonVerb with
  | "Get" ->
      ""
  | _ ->
      let theObj =
        if classname = "pool" || commonVerb = "New" then
          "session.Url"
        else
          ocaml_class_to_csharp_local_var classname
      in
      sprintf
        "\n\
        \            if (!ShouldProcess(%s, \"%s.%s\"))\n\
        \                return;\n"
        theObj
        (exposed_class_name classname)
        message.msg_name

and gen_csharp_api_call message classname commonVerb switch =
  let asyncPipe = gen_csharp_api_call_async_pipe in
  let passThruTask =
    if switch = "pipe" then
      asyncPipe
    else if switch = "passthru" || switch = "asyncpassthru" then
      print_pass_thru asyncPipe
    else
      ""
  in
  let syncPipe = gen_csharp_api_call_sync_pipe message classname in
  let passThruResult =
    match (switch, message.msg_result) with
    | "pipe", _ ->
        syncPipe
    | "passthru", None ->
        "\n\
        \                    if (PassThru)\n\
        \                        WriteWarning(\"-PassThru can only be used \
         with -Async for this cmdlet. Ignoring.\");"
    | "passthru", _ ->
        print_pass_thru syncPipe
    | _ ->
        ""
  in
  if message.msg_async then
    sprintf
      "\n\
      \                var contxt = _context as %s;\n\n\
      \                if (contxt != null && contxt.Async)\n\
      \                {%s%s\n\
      \                }\n\
      \                else\n\
      \                {%s%s\n\
      \                }\n"
      ( if commonVerb = "Invoke" then
          sprintf "Xen%sAction%sDynamicParameters"
            (ocaml_class_to_csharp_class classname)
            (cut_msg_name (pascal_case message.msg_name) "Invoke")
        else if commonVerb = "Get" then
          sprintf "Xen%sProperty%sDynamicParameters"
            (ocaml_class_to_csharp_class classname)
            (cut_msg_name (pascal_case message.msg_name) "Get")
        else
          "XenServerCmdletDynamicParameters"
      )
      (gen_csharp_api_call_async message classname commonVerb)
      passThruTask
      (gen_csharp_api_call_sync message classname commonVerb)
      passThruResult
  else
    sprintf "%s%s%s"
      ( if
          commonVerb = "Invoke"
          && is_message_with_dynamic_params classname message
        then
          sprintf
            "\n\
            \                var contxt = _context as \
             Xen%sAction%sDynamicParameters;\n\
            \                if (contxt == null)\n\
            \                    return;"
            (ocaml_class_to_csharp_class classname)
            (cut_msg_name (pascal_case message.msg_name) "Invoke")
        else if
          commonVerb = "Get" && is_message_with_dynamic_params classname message
        then
          sprintf
            "\n\
            \                var contxt = _context as \
             Xen%sProperty%sDynamicParameters;\n\
            \                if (contxt == null)\n\
            \                    return;"
            (ocaml_class_to_csharp_class classname)
            (cut_msg_name (pascal_case message.msg_name) "Get")
        else
          ""
      )
      (gen_csharp_api_call_sync message classname commonVerb)
      passThruResult

and print_pass_thru x =
  sprintf
    "\n\
    \                    if (PassThru)\n\
    \                    {%s\n\
    \                    }"
    x

and gen_csharp_api_call_async message classname commonVerb =
  let call params =
    sprintf "taskRef = %s.async_%s(%s);"
      (qualified_class_name classname)
      message.msg_name
      (gen_call_params_for classname message commonVerb params)
  in
  match invoke_overloads message classname commonVerb with
  | [] ->
      sprintf "\n                    %s\n" (call message.msg_params)
  | overloads ->
      gen_overload_chain call overloads

and gen_csharp_api_call_async_pipe =
  sprintf
    "\n\
    \                        XenAPI.Task taskObj = null;\n\
    \                        if (taskRef != \"OpaqueRef:NULL\")\n\
    \                        {\n\
    \                            taskObj = XenAPI.Task.get_record(session, \
     taskRef.opaque_ref);\n\
    \                            taskObj.opaque_ref = taskRef.opaque_ref;\n\
    \                        }\n\n\
    \                        WriteObject(taskObj, true);"

and gen_csharp_api_call_sync message classname commonVerb =
  match invoke_overloads message classname commonVerb with
  | [] -> (
    match message.msg_result with
    | None ->
        sprintf "\n                    %s.%s(%s);\n"
          (qualified_class_name classname)
          message.msg_name
          (gen_call_params classname message commonVerb)
    | Some (Ref _, _) ->
        sprintf "\n                    string objRef = %s.%s(%s);\n"
          (qualified_class_name classname)
          message.msg_name
          (gen_call_params classname message commonVerb)
    | Some (Set (Ref _), _) ->
        sprintf "\n                    var refs = %s.%s(%s);\n"
          (qualified_class_name classname)
          message.msg_name
          (gen_call_params classname message commonVerb)
    | Some (Map (_, _), _) ->
        sprintf "\n                    var dict = %s.%s(%s);\n"
          (qualified_class_name classname)
          message.msg_name
          (gen_call_params classname message commonVerb)
    | Some (x, _) ->
        sprintf "\n                    %s obj = %s.%s(%s);\n" (exposed_type x)
          (qualified_class_name classname)
          message.msg_name
          (gen_call_params classname message commonVerb)
  )
  | overloads ->
      (* The result has to be declared before the chain so that every branch
         assigns the same variable the rest of the cmdlet already reads. *)
      let declaration, assignment =
        match message.msg_result with
        | None ->
            ("", "")
        | Some (Ref _, _) ->
            ("string objRef = null;", "objRef = ")
        | Some (Set (Ref x), _) ->
            ( sprintf "List<XenRef<%s>> refs = null;" (exposed_class_name x)
            , "refs = "
            )
        | Some (Map (x, y), _) ->
            ( sprintf "Dictionary<%s, %s> dict = null;" (exposed_type x)
                (exposed_type y)
            , "dict = "
            )
        | Some (x, _) ->
            ( sprintf "%s obj = default(%s);" (exposed_type x) (exposed_type x)
            , "obj = "
            )
      in
      let call params =
        sprintf "%s%s.%s(%s);" assignment
          (qualified_class_name classname)
          message.msg_name
          (gen_call_params_for classname message commonVerb params)
      in
      let chain = gen_overload_chain call overloads in
      if declaration = "" then
        chain
      else
        sprintf "\n                    %s\n%s" declaration chain

(* Emits the run-time overload selection: a guarded branch per overload,
   longest first, ending in an unconditional else. *)
and gen_overload_chain call overloads =
  let branch index (params, _, guard) =
    match guard with
    | [] ->
        sprintf "                    else\n                        %s\n"
          (call params)
    | _ ->
        sprintf "                    %sif (%s)\n                        %s\n"
          ( if index = 0 then
              ""
            else
              "else "
          )
          (String.concat " || " guard)
          (call params)
  in
  "\n" ^ String.concat "" (List.mapi branch overloads)

and gen_csharp_api_call_sync_pipe message classname =
  match message.msg_result with
  | None ->
      sprintf
        "\n\
        \                        var obj = %s.get_record(session, %s);\n\
        \                        if (obj != null)\n\
        \                            obj.opaque_ref = %s;\n\
        \                        WriteObject(obj, true);"
        (qualified_class_name classname)
        (ocaml_class_to_csharp_local_var classname)
        (ocaml_class_to_csharp_local_var classname)
  | Some (Ref r, _) ->
      sprintf
        "\n\
        \                        %s obj = null;\n\n\
        \                        if (objRef != \"OpaqueRef:NULL\")\n\
        \                        {\n\
        \                            obj = %s.get_record(session, objRef);\n\
        \                            obj.opaque_ref = objRef;\n\
        \                        }\n\n\
        \                        WriteObject(obj, true);"
        (qualified_class_name r) (qualified_class_name r)
  | Some (Set (Ref r), _) ->
      sprintf
        "\n\
        \                        var records = new List<%s>();\n\n\
        \                        foreach (var _ref in refs)\n\
        \                        {\n\
        \                            if (_ref.opaque_ref == \"OpaqueRef:NULL\")\n\
        \                                continue;\n\n\
        \                            var record = %s.get_record(session, _ref);\n\
        \                            record.opaque_ref = _ref.opaque_ref;\n\
        \                            records.Add(record);\n\
        \                        }\n\n\
        \                        WriteObject(records, true);"
        (qualified_class_name r) (qualified_class_name r)
  | Some (Map (_, _), _) ->
      sprintf
        "\n\
        \                        Hashtable ht = \
         CommonCmdletFunctions.ConvertDictionaryToHashtable(dict);\n\
        \                        WriteObject(ht, true);"
  | Some (_, _) ->
      sprintf "\n                        WriteObject(obj, true);"

and gen_call_params classname message commonVerb =
  gen_call_params_for classname message commonVerb message.msg_params

and gen_call_params_for classname message commonVerb params =
  String.concat ", "
    ("session" :: gen_param_list classname params message commonVerb)

and gen_param_list classname params message commonVerb =
  let cutMessageName =
    cut_msg_name (ocaml_class_to_csharp_property message.msg_name) commonVerb
  in
  let get_param_name x =
    if is_class x classname then
      ocaml_class_to_csharp_local_var classname
    else if
      commonVerb = "Invoke"
      && List.mem (String.lowercase_ascii x.param_name) ["name"; "uuid"]
    then
      sprintf "contxt.%s" (ocaml_class_to_csharp_property x.param_name)
      ^ "Param"
    else if commonVerb = "Invoke" then
      sprintf "contxt.%s" (ocaml_class_to_csharp_property x.param_name)
    else if commonVerb = "Get" then
      sprintf "contxt.%s" (ocaml_class_to_csharp_property x.param_name)
    else if not (commonVerb = "New") then
      cutMessageName
    else
      ocaml_class_to_csharp_property x.param_name
  in
  let valueOfPair x =
    match x.param_type with
    | Map (u, v) ->
        sprintf
          "CommonCmdletFunctions.ConvertHashTableToDictionary<%s, %s>(%s.Value)"
          (exposed_type u) (exposed_type v) cutMessageName
    | _ ->
        cutMessageName ^ ".Value"
  in
  let api_call_param x =
    match x.param_type with
    | Map (u, v) ->
        sprintf "CommonCmdletFunctions.ConvertHashTableToDictionary<%s, %s>(%s)"
          (exposed_type u) (exposed_type v) (get_param_name x)
    | _ ->
        get_param_name x
  in
  let messageParams =
    List.filter (fun x -> not (is_class x classname)) message.msg_params
  in
  let restParams =
    List.filter (fun x -> is_class x classname) message.msg_params
  in
  let procParams = List.map get_param_name restParams in
  match commonVerb with
  | "Remove" -> (
    match messageParams with
    | [] ->
        procParams
    | [x] ->
        procParams @ [api_call_param x]
    | _ ->
        Printf.eprintf "%s" message.msg_name ;
        assert false
  )
  | "Add" -> (
    match messageParams with
    | [x] ->
        procParams @ [api_call_param x]
    | [_; y] ->
        procParams @ [cutMessageName ^ ".Key"; valueOfPair y]
    | _ ->
        Printf.eprintf "%s" message.msg_name ;
        assert false
  )
  | "Set" -> (
    match messageParams with
    | [x] ->
        procParams @ [api_call_param x]
    | [x; y]
      when not (obj_internal_type x.param_type = obj_internal_type y.param_type)
      ->
        procParams @ [cutMessageName ^ ".Key"; valueOfPair y]
    | hd :: tl ->
        let argList = ref [] in
        let hdtype = obj_internal_type hd.param_type in
        if List.for_all (fun x -> hdtype = obj_internal_type x.param_type) tl
        then (
          explode_array cutMessageName (List.length messageParams) argList ;
          procParams @ !argList
        ) else (
          Printf.eprintf "%s" message.msg_name ;
          assert false
        )
    | _ ->
        Printf.eprintf "%s" message.msg_name ;
        assert false
  )
  | _ -> (
    match params with
    | [] ->
        []
    | h :: tl ->
        api_call_param h :: gen_param_list classname tl message commonVerb
  )

and explode_array name length result =
  for i = length - 1 downto 0 do
    result := sprintf "%s[%s]" name (string_of_int i) :: !result
  done

(* The name of the dynamic parameter property generated for [param]. *)
and dynamic_param_property commonVerb param =
  if
    commonVerb = "Invoke"
    && List.mem (String.lowercase_ascii param.param_name) ["name"; "uuid"]
  then
    ocaml_class_to_csharp_property param.param_name ^ "Param"
  else
    ocaml_class_to_csharp_property param.param_name

(* A message gains a new C# overload every time parameters are added to it in a
   later release. Calling the newest overload unconditionally breaks against
   hosts that only know the older one (CA-431418), so the generated cmdlet has
   to choose at run time.

   Returns the overloads longest first, as (parameters, guard) pairs: [guard] is
   a disjunction that is true when the caller supplied any of the parameters
   this overload added. The final entry always has an empty guard and is the
   unconditional fallback to the overload published in the earliest release.

   Returns [] when no choice is needed, in which case the caller emits a single
   plain call exactly as before. *)
and invoke_overloads message classname commonVerb =
  if commonVerb <> "Invoke" || message.msg_params = [] then
    []
  else
    match group_params_per_release message.msg_params with
    | [] | [_] ->
        []
    | groups ->
        (* Accumulate the parameters released so far, pairing each prefix with
           the group that extended it. Prepending leaves the longest first. *)
        let rec build acc released = function
          | [] ->
              acc
          | group :: tl ->
              let released = released @ group in
              build ((released, group) :: acc) released tl
        in
        let guard_for added =
          added
          |> List.filter (fun p -> not (is_class p classname))
          |> List.map (fun p ->
              sprintf "contxt.Is%sSpecified"
                (dynamic_param_property commonVerb p)
          )
        in
        (* The oldest overload is the fallback, so it is never guarded: the
           parameters it takes are the ones every supported host accepts. *)
        let rec with_guards = function
          | [] ->
              []
          | [(params, added)] ->
              [(params, added, [])]
          | (params, added) :: tl ->
              (params, added, guard_for added) :: with_guards tl
        in
        let overloads = with_guards (build [] [] groups) in
        (* Every overload above the fallback must be selectable, otherwise the
           chain would emit an unreachable branch. *)
        let rec selectable = function
          | [] | [_] ->
              true
          | (_, _, []) :: _ ->
              false
          | _ :: tl ->
              selectable tl
        in
        if selectable overloads then
          overloads
        else
          []

(* The parameters whose presence selects an overload. Only these need to track
   whether the caller set them. *)
and overload_tracked_params message classname commonVerb =
  invoke_overloads message classname commonVerb
  |> List.filter (fun (_, _, guard) -> guard <> [])
  |> List.concat_map (fun (_, added, _) -> added)
  |> List.filter (fun p -> not (is_class p classname))
  |> List.map (fun p -> p.param_name)

let _ = main ()
