ifdef B_BASE
include $(B_BASE)/common.mk
REPO=$(call hg_loc,xen-api-libs)
else
MY_OUTPUT_DIR ?= $(CURDIR)/output
MY_OBJ_DIR ?= $(CURDIR)/obj
REPO ?= $(CURDIR)

RPM_SPECSDIR?=/usr/src/redhat/SPECS
RPM_SRPMSDIR?=/usr/src/redhat/SRPMS
RPM_SOURCEDIR?=/usr/src/redhat/SOURCES
XEN_RELEASE?=unknown
endif


.PHONY: srpm
srpm:
	hg archive -p xapi-0 -t tbz2 $(RPM_SOURCEDIR)/xapi-libs-0.tar.bz2
	rpmbuild --define "XEN_RELEASE $(XEN_RELEASE)" -bs --nodeps xapi-libs.spec

