#!/bin/sh

export REPO=/myrepos/xen-api-libs

set -e 
make clean; make cleanxen;
make uninstall; make uninstallxen; make binuninstall
make all && make bins && make install && make allxen && make installxen && make bininstall
