#!/bin/sh

PREFIX=ocaml/idl
ML=datamodel_lifecycle.ml

export XAPI_VERSION=${XAPI_VERSION:-0.0.0}
dune exec --profile=${PROFILE:-release} $PREFIX/gen_lifecycle.exe -- $* > "$ML"
if /usr/bin/cmp "$ML" "$PREFIX/$ML"; then
  echo "$ML is unchanged"
else
  test -s "$ML" && mv "$ML" "$PREFIX/$ML" && echo "$ML updated"
fi
