# Makefile to build the test guest agent

OCAMLC ?= ocamlc

.PHONY: all
all: gtserver
	@ :

gtserver:
	$(OCAMLC) -o $@ unix.cma gtmessages.ml gtcomms.ml gtlinuxops.ml gtserver_linux.ml	

.PHONY: clean
clean:
	rm -f gtserver
