FROM docker.io/ocaml/opam:centos-7-ocaml-4.13 as depext-gen
RUN opam repository set-url default https://github.com/edwintorok/xs-opam.git#4ba8b16c8f24d8a50578e50c1de35e9bf42a7a55 && \
  opam depext -l xs-toolstack >depexts.packages
