# syntax=docker/dockerfile:1
FROM docker.io/ocaml/opam:centos-7-ocaml-4.13
ENV DUNE_CACHE="enabled" DUNE_CACHE_STORAGE_MODE="copy"
RUN --mount=type=cache,target=/home/opam/.cache/dune,sharing=shared,uid=1000,gid=1000 --mount=type=cache,target=/home/opam/.opam/download-cache,sharing=locked,uid=1000,gid=1000 'opam' 'install' 'opam-monorepo'
RUN --mount=type=cache,target=/var/cache/yum,sharing=locked,uid=0,gid=0 'sudo' 'yum' 'install' '-y' 'epel-release' 'centos-release-xen' && \
  'sudo' 'yum' 'install' '-y' 'autoconf' 'gcc' 'gmp' 'gmp-devel' 'hwdata' 'kernel-headers' 'libffi-devel' 'libnl3' 'libnl3-devel' 'openssl-devel' 'pam-devel' 'pciutils-devel' 'perl-ExtUtils-MakeMaker' 'pkgconfig' 'python2' 'systemd-devel' 'which' 'xen-devel' 'xxhash-devel' 'xxhash-libs'
RUN 'echo' 'TODO: commit hash 2' && \
  'opam' 'repository' 'set-url' 'default' 'git+https://github.com/edwintorok/xs-opam'
RUN 'mkdir' '-p' 'workspace'
COPY --chown=1000:1000 [ "xapi.opam.locked", "workspace/xapi.opam.locked" ]
RUN --mount=type=cache,target=/home/opam/.cache/duniverse,sharing=shared,uid=1000,gid=1000 'rsync' '-a' '--whole-file' '--no-compress' '/home/opam/.cache/duniverse/' '/home/opam/workspace/duniverse/' && \
  'opam' 'monorepo' 'pull' '-r' '/home/opam/workspace' && \
  'rsync' '-a' '--whole-file' '--no-compress' '/home/opam/workspace/duniverse/' '/home/opam/.cache/duniverse/'
RUN --mount=type=cache,target=/home/opam/.cache/dune,sharing=shared,uid=1000,gid=1000 --mount=type=cache,target=/home/opam/.opam/download-cache,sharing=locked,uid=1000,gid=1000 'opam' 'install' '--ignore-pin-depends' '--deps-only' 'workspace/xapi.opam.locked' '--locked'
RUN 'opam' 'remove' 'sexplib'
RUN --mount=type=bind,rw,target=workspace/xapi,source=. --mount=type=cache,target=/home/opam/.cache/dune,sharing=shared,uid=1000,gid=1000 --mount=type=cache,target=/home/opam/workspace/xapi/_build,sharing=shared,uid=1000,gid=1000 'touch' 'workspace/dune-workspace' && \
  'ln' '-s' 'xapi/dune-project' 'workspace/dune-project' && \
  'cd' 'workspace/xapi' && \
  'opam' 'exec' '--' 'dune' 'build' '--profile=release' 'xapi.install' 'xe.install'
VOLUME [ "/home/opam/workspace/xapi/_build" ]
