(** Called in the autogenerated String_to_DM module *)

exception Failure of string

let set f (m: string) = 
  match Sexpr.of_string m with
  | SExpr.Node xs ->
      List.map (function SExpr.String x -> f x
		| _ -> raise (Failure m)) xs
  | _ -> raise (Failure m)

let map f g (m: string) = 
  match Sexpr.of_string m with
  | SExpr.Node xs ->
      List.map (function SExpr.Node [ SExpr.String k; SExpr.String v ] -> f k, g v
		| _ -> raise (Failure m)) xs
  | _ -> raise (Failure m)


