#!/bin/bash

echo "#!/bin/bash" > xencaml
ROOT=`cd .. && pwd`
echo "`pwd`/xencaml-bin.run -I /opt/xensource/lib/site-lib/stdext -I /opt/xensource/lib/site-lib/str -I /opt/xensource/lib/site-lib/xml-light2 -I /opt/xensource/lib/xmlm -I $ROOT/idl/ocaml_backend -I $ROOT/idl -I $ROOT/autogen/ -I $ROOT/http -I $ROOT/util \$@" >> xencaml
chmod 755 xencaml
