#!/bin/bash
#
# Copyright (c) Citrix Systems 2008. All rights reserved.
#
# Experimental backup script

# NB if this script returns non-zero then the host-backup CLI command will fail.

set -e

# Call pool-sync-database to synchronise the pool-database across all hosts in the pool.
xe pool-sync-database

# During restore the tar file is extracted over the backup partition which
# is then made bootable. Following a reboot the user must manually call
# "xe pool-restore-database" on the pool-database `/var/lib/xcp/state.db` backup file.

# Exclude everything under /tmp (as it is temporary) and everything under /var/crash
# (as it might contain large sparse files).  The directories themselves still need to
# exist, however, for xapi to function correctly.

tar --exclude 'tmp/*' --exclude 'tmp/.*' --exclude 'var/crash/*' --exclude 'var/crash/.*' \
    --exclude 'var/log/audit*' \
    --exclude 'var/xsconfig/*' --exclude 'var/xsconfig/.*' \
    --exclude 'var/xapi/[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*' \
    --warning='no-file-ignored' \
    --sparse --preserve-permissions --to-stdout --gzip --one-file-system -C / -c . 

