# manually derived from mypy'sy stubgen tool:
from typing import TextIO, Union

def openLog(lfile: Union[str, TextIO], level: int = ...) -> bool: ...
def closeLogs() -> None: ...
def logToStdout(level=...): ...
def logToStderr(level=...): ...
def logToSyslog(ident=..., level=..., facility=...) -> None: ...
def log(txt) -> None: ...
def logException(e) -> None: ...
def debug(*al, **ad) -> None: ...
def info(*al, **ad) -> None: ...
def warning(*al, **ad) -> None: ...
def error(*al, **ad) -> None: ...
def critical(*al, **ad) -> None: ...
