FROM docker.io/ocaml/opam:centos-7-ocaml-4.13
RUN --mount=type=cache,target=/var/cache/yum,sharing=locked sudo yum install -y epel-release centos-release-xen
RUN --mount=type=cache,target=/var/cache/yum,sharing=locked sudo yum install -y etcd /usr/sbin/ip
ENV DUNE_CACHE=enabled DUNE_CACHE_STORAGE_MODE=copy
# TODO: eventually remove default repo, but for now we need it as an easy way
#RUN opam repository add xs-opam https://github.com/xapi-project/xs-opam.git
RUN opam repository add xs-opam https://github.com/edwintorok/xs-opam.git
# have to rm default otherwise it'll try to fetch inconsistent set of packagees
RUN opam repository remove default
WORKDIR xapi

# first yes is to install depext plugin
# pinning is way too slow (it will do a git clone every time or rsync),
# so as a workaround install depext of xs-toolstack (which might be slightly
# out of date with the .opam files here though)

#  xen-devel is not in CentOS
RUN --mount=type=cache,target=/var/cache/yum,sharing=locked --mount=type=cache,target=/home/.opam/download-cache,uid=1000,gid=1000,sharing=locked opam --yes depext --yes xs-toolstack
RUN --mount=type=cache,target=/home/opam/.opam/download-cache,uid=1000,gid=1000,sharing=locked --mount=type=cache,target=/home/opam/.cache/dune,uid=1000,gid=1000 opam install polly
RUN --mount=type=cache,target=/home/opam/.opam/download-cache,uid=1000,gid=1000,sharing=locked --mount=type=cache,target=/home/opam/.cache/dune,uid=1000,gid=1000 opam install --deps-only xapi
