#!/bin/sh

TYPE=`echo ${XENBUS_PATH} | cut -f 2 -d '/'`
DOMID=`echo ${XENBUS_PATH} | cut -f 3 -d '/'`
DEVID=`echo ${XENBUS_PATH} | cut -f 4 -d '/'`

XAPI=/xapi/${DOMID}/hotplug/${TYPE}/${DEVID}

case "$1" in
add)
        xenstore-write "${XAPI}/hotplug" "online"
        ;;
remove)
        xenstore-rm "${XAPI}/hotplug"
        ;;
esac
