#!/bin/sh

# Build the XenCloud repos in a build appliance

set -e

UPSTREAM_URL=http://hg.uk.xensource.com/carbon/trunk
REPO=/root/repo

if [ -z "$(cat /etc/redhat-release | grep 'XenCloud DDK')" ]; then
   echo WARNING: this does not appear to be a XenCloud build appliance
fi

echo "Placing repositories in ${REPO}"
mkdir -p ${REPO}

for repo in xen-dist-ocaml.hg xen-api-libs.hg xen-api.hg; do
    if [ ! -e "$REPO/$repo" ]; then
	echo Cloning $UPSTREAM_URL/$repo to $REPO/$repo
	hg clone $UPSTREAM_URL/$repo $REPO/$repo
    else
	echo "$REPO/$repo already exists; no need to re-clone"
    fi
done

echo "Building ocaml packages"
cd $REPO/xen-dist-ocaml.hg
make
make clean
echo "Building XenCloud-specific libraries"
cd $REPO/xen-api-libs.hg
./rebuild
echo "Building XenCloud toolstack"
cd $REPO/xen-api.hg
make
make install
echo "XenCloud toolstack in $REPO/xen-api.hg/dist/staging"
