#!/bin/sh

@LIBEXECDIR@/daily-license-check >/dev/null 2>&1

EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t daily-license-check "ALERT exited abnormally with [$EXITVALUE]"
fi
exit 0
