#!/bin/sh

# do a manual clean-up of likewise
/opt/likewise/bin/domainjoin-cli configure --disable pam
/opt/likewise/bin/domainjoin-cli configure --disable nsswitch
/opt/likewise/bin/domainjoin-cli configure --disable krb5
/etc/init.d/lsassd stop
/etc/init.d/netlogond stop
/etc/init.d/npcmuxd stop
/etc/init.d/gpagentd stop
/etc/init.d/lwmgmtd stop
/etc/init.d/eventlogd stop
/etc/init.d/dcerpcd stop
chkconfig --del lsassd
chkconfig --del netlogond
chkconfig --del npcmuxd
chkconfig --del gpagentd
chkconfig --del lwmgmtd
chkconfig --del eventlogd
chkconfig --del dcerpcd
rm -f /var/lib/likewise/db/*.db

