#!/bin/sh

# Example on-master-start script

# Source function library.
. /etc/init.d/functions

start() {
	echo -n $"Assuming role of master: "
	touch /tmp/master
	echo -n $"OK"
	success $"OK"
	echo
	return 0
}

stop() {
	echo -n $"Dropping role of master: "
	rm -f /tmp/master
	echo
	return 0
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac
