#!/bin/sh
PATH=/usr/bin:/bin
umask 022
tail_args="-n "
echo "Unpacking..."
outname=install.sfx.$$
trap 'rm -f $outname; exit 1' HUP INT QUIT TERM
tail ${tail_args}+16 $0 > $outname
chmod +x $outname
echo "Extracting..."
./$outname
echo "Executing..."
./install.sh
rm -f $outname
# Line 15 -- data follows!
