#!/usr/bin/python
#
# Copyright (c) Citrix Systems 2007-2011
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; version 2.1 only. with the special
# exception on linking described in file LICENSE.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.


import sys, os, time, resource, os.path

DOMID=int(sys.argv[1])
LOGFILE=sys.argv[2]

os.system("xenstore-write /local/domain/%d/qemu-pid %d\n" % (DOMID, os.getpid()))

IS_SDK = (int(os.popen("xenstore-read domid").read()) != 0)

if IS_SDK:
    time.sleep(2)
    os.system("xenstore-write -s /local/domain/%d/device-misc/dm-ready 1" % DOMID)
    os.system("xenstore-write -s /local/domain/%d/console/vnc-port %d\n" % (DOMID, 6900+DOMID))
    while True:
        time.sleep(1)

log = open(LOGFILE, "wa")
log.write("qemu-dm-wrapper in python:\n")
log.write("Using domid: %d\n" % DOMID)
log.write("Arguments: %s\n" % " ".join(sys.argv[2:]))
log.flush()

# redirect stdout to append to logfile
os.dup2(log.fileno(), 1)

# redirect stderr to stdout (which now goes to the log)
os.dup2(1, 2)

os.execve("/usr/lib/xen/bin/qemu-dm", sys.argv[2:], os.environ)
