#!/bin/bash
#
# Copyright (c) Citrix Systems 2008. All rights reserved.
#
set -e
INV=@INVENTORY@
INTF=$1
TMP=/tmp/rewrite-inventory.tmp.$$

error () {
	trap - EXIT ERR
	rm -f ${TMP}
}
trap error EXIT ERR

cat ${INV} | grep -v ^MANAGEMENT_INTERFACE > ${TMP}
echo "MANAGEMENT_INTERFACE='$INTF'" >> ${TMP}
mv ${TMP} ${INV}

"@LIBEXECDIR@/update-mh-info" $INTF
