#!/bin/sh

set -e

if [ $# -ne 1 ] ; then
   echo "usage $0 <hostname>" 1>&2
   exit 1
fi

HOSTNAME=$1

# Update system configuration
sed -i -e "s/^\(HOSTNAME=\).*$/\1$1/g" /etc/sysconfig/network

# Set current hostname
hostname "$HOSTNAME"

exit 0
