#!/bin/sh
#
# Copyright (c) Citrix Systems 2008. All rights reserved.
#

# Simple script to upload a file or directory. If this script
# exits with code 0 we assume the upload was successful..

CRASH=$1
URL=$2
PROXY=$3

export http_proxy=$PROXY
export ftp_proxy=$PROXY

# If it's a directory then tar it up and stream. Otherwise just send the file
if [ -d $CRASH ];
then
  tar --sparse -cz $CRASH | curl -T - $URL 2>&1
else
  cat $CRASH | curl -T - $URL 2>&1
fi
