#!/bin/sh

set -e

die()
{
  echo $@ >&2
  exit 1
}

usage()
{
  die "Usage: $0 [--sr=<sr>] <iso>"
}

. /etc/xensource-inventory

while [ -n "$1" ]; do
  case "$1" in
    --sr=*)
      sr_uuid=${1#--sr=};;
    -*)
      usage;;
    *)
      break;;

  esac
  shift
done

iso="$1"
[ -n "$iso" ] || usage

update_uuid=$(xe update-upload file-name="$iso" ${sr_uuid:+sr-uuid=$sr_uuid})
trap "xe update-pool-clean uuid=$update_uuid" EXIT ERR
trap "xe update-destroy uuid=$update_uuid" ERR
xe update-apply uuid=$update_uuid host=$INSTALLATION_UUID
