#!/bin/sh

set -e

die()
{
  echo $@ >&2
  exit 1
}

usage()
{
  die "Usage: $0 [--sr=<sr>] <iso>"
}

while [ -n "$1" ]; do
  case "$1" in
    --sr=*)
      sr_uuid=${1#--sr=};;
    -*)
      usage;;
    *)
      break;;

  esac
  shift
done

iso="$1"
[ -n "$iso" ] || usage

if [ -z "$sr_uuid" ]; then
  pool_uuid=$(xe pool-list --minimal)
  sr_uuid=$(xe pool-param-get uuid=$pool_uuid param-name=default-SR --minimal)
fi

vdi_uuid=$(xe vdi-create sr-uuid=$sr_uuid name-label="$(basename $iso)" virtual-size=0)
trap "xe vdi-destroy uuid=$vdi_uuid" EXIT
xe vdi-import uuid=$vdi_uuid filename=$1
update_uuid=$(xe update-introduce vdi-uuid=$vdi_uuid)
xe update-apply uuid=$update_uuid
