#!/bin/bash
# Copyright (c) 2008,2009,2010 Citrix Systems, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; version 2.1 only. with the special
# exception on linking described in file LICENSE.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#

POOLCONF=`cat @ETCDIR@/pool.conf`

service xapi stop
service v6d stop
service squeezed stop
service perfmon stop
[ -e /tmp/do-not-use-networkd ] || service xcp-networkd stop
service fe stop
if [ $POOLCONF == "master" ]; then
	@ETCDIR@/master.d/03-mpathalert-daemon stop;
fi

set -e

if [ $POOLCONF == "master" ]; then
	@ETCDIR@/master.d/03-mpathalert-daemon start;
fi
service fe start
[ -e /tmp/do-not-use-networkd ] || service xcp-networkd start
service perfmon start
service squeezed start
service v6d start
service xapi start
echo "done."
