#!/bin/sh

set -eu

GRAPH="../../graph.native -h $1 -u $2 -pw $3"
DOTARGS="-Tpng -Ktwopi -Goverlap=false"

${GRAPH} VM VBD VDI SR > vm-disks.dot
${GRAPH} VM VIF network > vm-network.dot
${GRAPH} host PIF network > host-network.dot

for i in vm-disks vm-network host-network
do
  dot ${DOTARGS} $i.dot > $i.png
done
