#!/bin/sh

DOTARGS="-Tpng -Ktwopi -Goverlap=false"
GRAPH=./graph

${GRAPH} VM VBD VDI SR > vm-disks.dot
${GRAPH} VM VIF network > vm-network.dot
${GRAPH} host PIF network > host-network.dot

for i in vm-disks.dot vm-network.dot host-network.dot
do
  dot ${DOTARGS} $i > $i.png
done
