(* This file is autogenerated.  Grep for e17512ce-ba7c-11df-887b-0026b9799147 (random uuid) to see where it comes from. ;o) *) 
 let product_version () = Inventory.lookup ~default:"" "PRODUCT_VERSION" 
 let product_version_text () = Inventory.lookup ~default:"" "PRODUCT_VERSION_TEXT" 
 let product_version_text_short () = Inventory.lookup ~default:"" "PRODUCT_VERSION_TEXT_SHORT" 
 let platform_name () = Inventory.lookup ~default:"" "PLATFORM_NAME" 
 let platform_version () = Inventory.lookup ~default:"0.0.0" "PLATFORM_VERSION" 
 let product_brand () = Inventory.lookup ~default:"" "PRODUCT_BRAND" 
 let build_number () = Inventory.lookup ~default:"" "BUILD_NUMBER" 
