module C = Configurator.V1

let config = Hashtbl.create 5

(** [flag arg ~doc ~default] sets the default value of [arg] to [default].
    Allow the user to override from the command-line with [--arg], and show
    [doc] on [--help].
    *)
let flag arg ~doc ~default =
  let key = String.uppercase_ascii arg in
  Hashtbl.replace config key default ;
  ("--" ^ arg, Arg.String (Hashtbl.replace config key), doc)

let libdir_default =
  (* This is the same that [dune install] does by default when invoked without --prefix.
     This ensures that files end up in the right place regardless of whether [opam] is used or not.
     We unconditionally use `--prefix` on the command-line so we need to use this too.
  *)
  Findlib.default_location ()

let args =
  [
    flag "prefix" ~doc:"DIR Final install destination" ~default:"/usr"
    (* ensures bin and sbin end up in right places *)
  ; flag "libdir" ~doc:"DIR Directory where library files are copied"
      ~default:libdir_default
  ]
  |> Arg.align

let () =
  C.main ~args ~name:"message-switch" @@ fun _c ->
  let lines =
    "# Warning - this file is autogenerated by the configure script"
    ::
    "# Do not edit"
    ::
    (config
    |> Hashtbl.to_seq
    |> (Seq.map @@ fun (k, v) -> Printf.sprintf "%s=%s" k v)
    |> List.of_seq
    )
  in
  List.iter print_endline lines
