# Minimal stub for xcp.logger module
def debug(*al, **ad) -> None: ...
def error(*al, **ad) -> None: ...
def warning(*al, **ad) -> None: ...
def logToStdout(level) -> bool: ...
def logToSyslog(level) -> bool: ...
